### ISSUE TITLE
Error bundling with Metro Bundler

### ISSUE THREAD

**Issue by Jelomite** [listenzz/react-native-modal-translucent#10]
I've installed the package as instructed in the README.md, but once I run the project, I get an error.  This error explains everything, can you please fix the problem? 

--------
```bash
error: bundling failed: Error: While trying to resolve module `react-native-modal-translucent` from file `/home/suerflowz/Projects/twist-native/src/views/home.js`, the package `/home/suerflowz/Projects/twist-native/node_modules/react-native-modal-translucent/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/suerflowz/Projects/twist-native/node_modules/react-native-modal-translucent/index`. Indeed, none of these files exist:

  * `/home/suerflowz/Projects/twist-native/node_modules/react-native-modal-translucent/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/home/suerflowz/Projects/twist-native/node_modules/react-native-modal-translucent/index/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/home/suerflowz/Projects/twist-native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:61:15)
    at DependencyGraph.resolveDependency (/home/suerflowz/Projects/twist-native/node_modules/metro/src/node-haste/DependencyGraph.js:218:16)
    at Object.resolve (/home/suerflowz/Projects/twist-native/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/home/suerflowz/Projects/twist-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/suerflowz/Projects/twist-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /home/suerflowz/Projects/twist-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/home/suerflowz/Projects/twist-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
    at /home/suerflowz/Projects/twist-native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:309:15
 BUNDLE  [android, dev] ./index.js ▓▓▓░░░░░░░░░░░░░ 23.8% (253/545), failed.
```

**Comment by TheSixth** [comment]
same issue. any way to solve this problem?
